#!/bin/bash

FILE_DIR=$(dirname $1)
FILE_NAME=$(basename -- $1)
FILE=${FILE_NAME%.*}
EXT=${FILE_NAME##*.}
OUT=$FILE_DIR/$FILE-$EXT.runsrc
clear

if [ ! -z "$EXT" ]; then
  case $EXT in
	c)
		gcc $1 -o $OUT && chmod a+x $OUT && ./$OUT
        rm -rf $OUT
		;;
	cpp)
		g++ $1 -o $OUT && chmod a+x $OUT && ./$OUT
        rm -rf $OUT
        ;;
	*)
		echo "I can run that ;("
		;;
  esac
fi
